apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config-file
  labels:
    app: prom
data:
 prometheus.yml: |-
  global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
  alerting:
    alertmanagers:
    - static_configs:
      - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
  scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - localhost:9090

  - job_name: node1
    static_configs:
    - targets:
      - 192.168.99.101:9100

  - job_name: apache
    static_configs:
    - targets:
      - 192.168.99.101:1234

  - job_name: docker
    static_configs:
    - targets:
      - 192.168.99.101:9117